runtime: python312
env: standard

handlers:
  - url: /
    secure: always
    static_files: dist/pfclient/browser/index.csr.html
    upload: dist/pfclient/browser/.*

  - url: /(.*\.js)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/pfclient/browser/\1
    upload: dist/pfclient/browser/.*\.js

  - url: /(.*\.css)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/pfclient/browser/\1
    mime_type: text/css
    upload: dist/pfclient/browser/.*\.css

  - url: /.*
    secure: always
    static_files: dist/pfclient/browser/index.csr.html
    upload: dist/pfclient/browser/.*
