export const transactions = [
  {
    id: 1,
    amount: 250.75,
    date: '2024-10-01',
    destination: 'Amazon',
    alias: 'Shopping',
    category: 2,
    subcategory: 21,
    notes: 'Bought electronics',
    is_saving: false,
    is_payment: false,
    is_expense: true,
    is_deleted: false,
    is_income: false,
    is_merge: false,
    merge_id: null,
    delete_reason: '',
    account: 101,
    source: 201,
    category_text: 'Shopping',
    subcategory_text: 'Electronics',
    account_name: 'Checking Account',
    account_type: 'Bank',
    year: 2024,
    month: 10,
    month_text: 'October',
  },
  {
    id: 2,
    amount: 1500.0,
    date: '2024-10-05',
    destination: 'Salary',
    alias: 'Monthly Pay',
    category: 1,
    subcategory: 10,
    notes: 'Monthly salary',
    is_saving: false,
    is_payment: false,
    is_expense: false,
    is_deleted: false,
    is_income: true,
    is_merge: false,
    merge_id: null,
    delete_reason: '',
    account: 102,
    source: 202,
    category_text: 'Income',
    subcategory_text: 'Salary',
    account_name: 'Savings Account',
    account_type: 'Bank',
    year: 2024,
    month: 10,
    month_text: 'October',
  },
  {
    id: 3,
    amount: 500.0,
    date: '2024-10-10',
    destination: 'Transfer to Savings',
    alias: 'Savings Transfer',
    category: 3,
    subcategory: 31,
    notes: 'Transfer to high-yield savings',
    is_saving: true,
    is_payment: false,
    is_expense: false,
    is_deleted: false,
    is_income: false,
    is_merge: false,
    merge_id: null,
    delete_reason: '',
    account: 103,
    source: 203,
    category_text: 'Savings',
    subcategory_text: 'High-Yield Savings',
    account_name: 'High-Yield Savings',
    account_type: 'Savings',
    year: 2024,
    month: 10,
    month_text: 'October',
  },
  {
    id: 4,
    amount: 100.0,
    date: '2024-10-15',
    destination: 'Electricity Bill',
    alias: 'Utilities',
    category: 4,
    subcategory: 41,
    notes: 'Monthly electricity bill',
    is_saving: false,
    is_payment: true,
    is_expense: true,
    is_deleted: false,
    is_income: false,
    is_merge: false,
    merge_id: null,
    delete_reason: '',
    account: 104,
    source: 204,
    category_text: 'Utilities',
    subcategory_text: 'Electricity',
    account_name: 'Checking Account',
    account_type: 'Bank',
    year: 2024,
    month: 10,
    month_text: 'October',
  },
  {
    id: 5,
    amount: 300.0,
    date: '2024-10-18',
    destination: 'Groceries',
    alias: 'Shopping',
    category: 2,
    subcategory: 22,
    notes: 'Weekly groceries',
    is_saving: false,
    is_payment: false,
    is_expense: true,
    is_deleted: false,
    is_income: false,
    is_merge: false,
    merge_id: null,
    delete_reason: '',
    account: 105,
    source: 205,
    category_text: 'Shopping',
    subcategory_text: 'Groceries',
    account_name: 'Checking Account',
    account_type: 'Bank',
    year: 2024,
    month: 10,
    month_text: 'October',
  },
];
