export const payees = [
  {
    id: 1,
    destination: 'Tokyo',
    destination_original: 'Original Tokyo',
    destination_eng: 'Tokyo (ENG)',
    category: 1,
    category_type: 1,
    category_type_text: 'Expense',
    category_text: 'Category 1',
    subcategory: 10,
    subcategory_text: 'Subcategory 10',
    keywords: 'keyword1, example1',
  },
  {
    id: 2,
    destination: 'New York',
    destination_original: 'Original New York',
    destination_eng: 'New York (ENG)',
    category: 2,
    category_type: 2,
    category_type_text: 'Income',
    category_text: 'Category 2',
    subcategory: 20,
    subcategory_text: 'Subcategory 20',
    keywords: 'keyword2, example2',
  },
  {
    id: 3,
    destination: 'Paris',
    destination_original: 'Original Paris',
    destination_eng: 'Paris (ENG)',
    category: 3,
    category_type: 1,
    category_type_text: 'Expense',
    category_text: 'Category 3',
    subcategory: 30,
    subcategory_text: 'Subcategory 30',
    keywords: 'keyword3, example3',
  },
  {
    id: 4,
    destination: 'London',
    destination_original: 'Original London',
    destination_eng: 'London (ENG)',
    category: 4,
    category_type: 2,
    category_type_text: 'Income',
    category_text: 'Category 4',
    subcategory: 10,
    subcategory_text: 'Subcategory 10',
    keywords: 'keyword4, example4',
  },
  {
    id: 5,
    destination: 'Berlin',
    destination_original: 'Original Berlin',
    destination_eng: 'Berlin (ENG)',
    category: 1,
    category_type: 1,
    category_type_text: 'Expense',
    category_text: 'Category 1',
    subcategory: 20,
    subcategory_text: 'Subcategory 20',
    keywords: 'keyword5, example5',
  },
];
